package com.example.demo.domain;

import java.util.List;

public class Vote {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_id
     *
     * @mbg.generated
     */
    private Long voteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.vote_title
     *
     * @mbg.generated
     */
    private String voteTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote.create_by
     *
     * @mbg.generated
     */
    private Long createBy;

    private List<VoteOption> voteOption;

    public List<VoteOption> getVoteOption() {
        return voteOption;
    }

    public void setVoteOption(List<VoteOption> voteOption) {
        this.voteOption = voteOption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_id
     *
     * @return the value of vote.vote_id
     *
     * @mbg.generated
     */
    public Long getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_id
     *
     * @param voteId the value for vote.vote_id
     *
     * @mbg.generated
     */
    public void setVoteId(Long voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.vote_title
     *
     * @return the value of vote.vote_title
     *
     * @mbg.generated
     */
    public String getVoteTitle() {
        return voteTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.vote_title
     *
     * @param voteTitle the value for vote.vote_title
     *
     * @mbg.generated
     */
    public void setVoteTitle(String voteTitle) {
        this.voteTitle = voteTitle == null ? null : voteTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote.create_by
     *
     * @return the value of vote.create_by
     *
     * @mbg.generated
     */
    public Long getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote.create_by
     *
     * @param createBy the value for vote.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(Long createBy) {
        this.createBy = createBy;
    }
}