package com.example.demo.domain;

public class VoteRecord extends VoteRecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_record.vote_id
     *
     * @mbg.generated
     */
    private Long voteId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_record.vote_id
     *
     * @return the value of vote_record.vote_id
     *
     * @mbg.generated
     */
    public Long getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_record.vote_id
     *
     * @param voteId the value for vote_record.vote_id
     *
     * @mbg.generated
     */
    public void setVoteId(Long voteId) {
        this.voteId = voteId;
    }
}