package com.example.demo.mapper;

import com.example.demo.domain.VoteOption;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;
@Mapper
public interface VoteOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long voteOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int insert(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int insertSelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    VoteOption selectByPrimaryKey(Long voteOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteOption record);

    List<VoteOption> selectListvoteOptionByvoteId(Long voteId);
}