package com.example.demo.mapper;

import com.example.demo.domain.VoteOption;

public interface VoteOptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long voteOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int insert(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int insertSelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    VoteOption selectByPrimaryKey(Long voteOptionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(VoteOption record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_option
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(VoteOption record);
}