package com.example.demo.mapper;

import com.example.demo.domain.VoteRecordKey;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface VoteRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(VoteRecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbg.generated
     */
    int insert(VoteRecordKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_record
     *
     * @mbg.generated
     */
    int insertSelective(VoteRecordKey record);
}